// background.js

const closingTabIds = new Set();

chrome.tabs.onCreated.addListener((tab) => {
  if (tab.windowId) {
    checkTabLimit(tab.windowId);
  }
});

chrome.tabs.onAttached.addListener((tabId, attachInfo) => {
  checkTabLimit(attachInfo.newWindowId);
});

async function checkTabLimit(windowId) {
  try {
    const tabs = await chrome.tabs.query({ windowId: windowId });
    // Filter out tabs that are currently being processed to avoid race conditions
    const activeTabs = tabs.filter(t => !closingTabIds.has(t.id));
    
    const LIMIT = 3;
    if (activeTabs.length > LIMIT) {
      // Sort tabs by their unique ID. Smaller IDs were created earlier in the browser session.
      let sortedTabs = activeTabs.sort((a, b) => a.id - b.id);
      let oldestTab = sortedTabs[0];
      
      closingTabIds.add(oldestTab.id);
      await summarizeAndClose(oldestTab.id);
      closingTabIds.delete(oldestTab.id); // the tab is removed, but we clear it from our set just in case
    }
  } catch (e) {
    console.error("Tab tracking error:", e);
  }
}


async function summarizeAndClose(tabId) {
  try {
    const tab = await chrome.tabs.get(tabId);
    
    // Prevent errors on internal pages
    if (!tab.url || tab.url.startsWith('chrome://') || tab.url.startsWith('edge://') || tab.url.startsWith('about:')) {
      saveSummary(tab.title || "Unknown", tab.url, "Internal browser page, cannot extract content.");
      chrome.tabs.remove(tabId);
      return;
    }

    let extractedText = null;
    try {
      // Use chrome.scripting to inject and extract content
      const results = await chrome.scripting.executeScript({
        target: { tabId: tabId },
        func: () => document.body ? document.body.innerText : ''
      });
      if (results && results[0] && results[0].result) {
        extractedText = results[0].result;
      }
    } catch (e) {
      console.warn("Script injection failed. Might be a restricted page.", e);
    }
    
    let summaryText = "Could not retrieve content. The page might restrict extensions a restricted URL.";
    if (extractedText) {
      summaryText = await generateSummary(extractedText);
    }
    
    saveSummary(tab.title || "Unknown", tab.url, summaryText);
    chrome.tabs.remove(tabId);

  } catch (err) {
    console.error("Error summarizing and closing tab:", err);
  }
}

async function generateSummary(text) {
  let cleanText = text.replace(/\s+/g, ' ').trim();
  if (cleanText.length === 0) return "No readable text found on page.";
  
  // To avoid hitting size limits on gigantic pages, clip text to ~20,000 characters
  if (cleanText.length > 20000) {
    cleanText = cleanText.substring(0, 20000);
  }

  return new Promise((resolve) => {
    chrome.storage.local.get(['geminiApiKey'], async (result) => {
      const apiKey = result.geminiApiKey ? result.geminiApiKey.trim() : null;
      
      if (!apiKey) {
         // Fallback if no API key is provided
         let fallbackSummary = cleanText.length <= 250 ? cleanText : cleanText.substring(0, 250) + "...";
         resolve("[No API Key Set - Check Options] " + fallbackSummary);
         return;
      }

      try {
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=${apiKey}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [{
              parts: [{
                text: "Summarize the following webpage content into a brief, easy to read paragraph of 2 to 3 sentences max, ignore any text that is unimportant to the core content of the page:\n\n" + cleanText
              }]
            }]
          })
        });

        if (!response.ok) {
           const errorBody = await response.text();
           console.error("Gemini API Error", response.status, errorBody);
           resolve(`API Error ${response.status}: ${errorBody.substring(0, 100)}...`);
           return;
        }

        const data = await response.json();
        if (data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts[0]) {
           resolve(data.candidates[0].content.parts[0].text);
        } else {
           resolve("No summary generated by API.");
        }
      } catch (e) {
        console.error("Fetch error", e);
        resolve("Exception caught while summarizing: " + e.message);
      }
    });
  });
}

function saveSummary(title, url, summary) {
  chrome.storage.local.get(['summaries'], (result) => {
    const summaries = result.summaries || [];
    summaries.unshift({
      id: Date.now().toString(),
      title: title,
      url: url,
      summary: summary,
      timestamp: new Date().toISOString()
    });
    
    // Keep max 50 summaries
    chrome.storage.local.set({ summaries: summaries.slice(0, 50) });
  });
}
